apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: LoadBalancer
  selector:
    app: nextjs
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30088  # Can be any value between 30000-32767
