apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://127.0.0.1:59826
    certificate-authority-data: |
      MIIDITCCAgmgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTI1MDUyMjE3NTYzN1oXDTI4MDUyMjE3NTYzN1owMTEXMBUGA1UE
      ChMOc3lzdGVtOm1hc3RlcnMxFjAUBgNVBAMTDW1pbmlrdWJlLXVzZXIwggEiMA0G
      CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDaOTL6ygp46aqIBzCE9etomDc5jvFX
      4GrDiaXH4T9UFKhopddyWZ4Wus+Wb1B3oMGHRu8lTJ7NVO/T972Eftrj33JxmZIA
      2TaA9Uh8VZX+pzxbucFO+ddmO3PrQEBn+yxiqh1oCG/oij1oM+YSjdeex9btPsuw
      wkp00K66KUvwaY+zNkaMtMWeV0zBVv4jf3K9KOy0bH6oWlY8C6icjKlMYNpW7zIM
      YHkt2FfO3BWW8ehIef869huc6mcqHQyu0Vfeq6iIq7E1aUVM5Fd3Mz+Pzwz10vSU
      YybLZtEE8jxeCv01/wVTslKkI8KBKT1i+BVY9YutOAh6reiUhli9JN9rAgMBAAGj
      YDBeMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
      AwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBRWzM61NvpzXDMkOgec7v1n8cYX
      rjANBgkqhkiG9w0BAQsFAAOCAQEAaQVpS4R71noVKgGZ42FcDZldI4B87V9iHlGf
      QmXZV3JxD2RWpaSlzU9RA6HWoSxVr28lUoPJRdLRR8+W7yLDaK7BOxiELkTwCxHl
      9rE3C2nGYbfOU3XNeXZY4wXDqspqbrDeTWxN6fBdmZ70aNW6CcF+Yh0tHxRH4V/q
      DC1olm89EvlB9MM3DOQFW4IVsDmmkaKFg9fMJd0MxYRYbszg4pqA4tdzyYBO/YcD
      uD9zmYG+zoQlqdm1T1Oj8MvIHhf4d2DOtYXeGgTnlnh6ETvM7xaWT4N+Rk6rCfUX
      xRM5ZOvltBRjNJuwGhDbABPXXVuZwJXWvhX3eqGml5qYHzh6uA==
users:
- name: my-user
  user:
    client-certificate-data: |
      MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTI1MDUwODA5MzgwOFoXDTM1MDUwNzA5MzgwOFowFTETMBEGA1UE
      AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKIc
      O5sNy9naF88/kH0tc7rEhh71MhFCVgQqGFdakvpXEOu2fBH1YlCoKYouT8C1YLsR
      wHswxYJtvtwpyZnC9TTppyOeWINxZEQgx/Da0oFCKz8cnRA1g/v8uIfnjGn0Vjwl
      8TXAUpDkWCJx53ejOjFHKmIkOf+b7iNe0/8LWCqvN73ILbxPVhkchq97l9P/bfSo
      +o+XCsiwM/l4gwancoa85Fclnegjw4dMMJO9ApuPfwTtmMV4ODWQkUf5LnBZQswg
      n+JB2QU6lI8t4jW5Quv4wKHEx0Cv74oTTh0fstXwKTEGHgOC2+4byohNypUieIIg
      sXRqrmlkM/G3Su0HbusCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
      MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
      BBRWzM61NvpzXDMkOgec7v1n8cYXrjANBgkqhkiG9w0BAQsFAAOCAQEAiJXHkiBG
      EKsKPlR1ixBgefL93xgLUlmv/4vWlR+2yW/G4pzbUTRWaKwaeMhAfZ9uTqb3R0zu
      nkcXxKKyUrmHH8m0W00HuGMgWwozUKPyJ4AdhVgc05yfb2qvLPQp4W5CMuzfDHOe
      zJiJ8ugoJB+zSPNlt7mW2c0crNbPy/GCVlPyLXlRvu+c/6GCN+BK+1JAlFU8n1Dw
      h5ZLX74fX45gJZfG0XqzrT/YEY1hlTZyrkknRhvcK/wIFi82RERSUVUSQD0jCGcR
      OxOZPUYkJLH2Xgd7JvS5d9GxAa/9ydRUN+PjuGEtEeS4Pm/IO5Xzi+jJuYkIAOoK
      Ppzz2/BoWt5gpg==
    client-key-data: |
      MIIEpAIBAAKCAQEA2jky+soKeOmqiAcwhPXraJg3OY7xV+Bqw4mlx+E/VBSoaKXX
      clmeFrrPlm9Qd6DBh0bvJUyezVTv0/e9hH7a499ycZmSANk2gPVIfFWV/qc8W7nB
      TvnXZjtz60BAZ/ssYqodaAhv6Io9aDPmEo3XnsfW7T7LsMJKdNCuuilL8GmPszZG
      jLTFnldMwVb+I39yvSjstGx+qFpWPAuonIypTGDaVu8yDGB5LdhXztwVlvHoSHn/
      OvYbnOpnKh0MrtFX3quoiKuxNWlFTORXdzM/j88M9dL0lGMmy2bRBPI8Xgr9Nf8F
      U7JSpCPCgSk9YvgVWPWLrTgIeq3olIZYvSTfawIDAQABAoIBABaAq3cc+nN5dPJN
      +3zadwn0GE3BJbXwGFJNkWDJI2SiNLOF1m+eOiUR4nIazGtpkktGz0ZDXmTCC3EK
      LOrKwfuZgQ2hzmJ0A6DMqkrX8H2v9RNoVjy0mreaDdwGZh3S0sLh0+J0bEXIa4ih
      QWpMYh2nccxJG2wAvPjKxBnCRGhn6YCRjimA4b+MqcRMI+XNWbb2CPlt0sojB3m7
      8Z+r7BRKWLhq0rIdWQAptL5TOIMqLt4hYVSWpaGvnANwFTNCbfAGNLBwI1hSsmYS
      oTsE26mYpI7zOBlz5Z1cqKj1bX3iYBf+Yo6pmKpDNJKcl7kXyMlE6SZ1mR1pJMGI
      x0kqJKkCgYEA6uE0FrxDbs9uJKyAynVTmRL6+wV2t4AcH5NZ3IpHK+rY5NHPoGZ4
      EoEVfkwlQghuw88He/FKuIP6Wm8ON0n0d3Qv7r6r9FKY1s5pKfFKQ5Fkx6X1fqlX
      dP6VTnM+bX0Ak2C6CQ+P6/jdh4SzSdybEG9UPOJu9kR2+p5r1lCMxuMCgYEA5OWW
      k9t6ytO5c6vh/uEX2kk/MvZXmNJTsY42GHTTO+P7L8+XlWfOW6hjDYX4EFaY6EMR
      F2TTcTwlSu9L1fOql3S/p9IQmHqlz6p3BHTxghNv9zq6aHTL9Pm/CUxaXKZPknqM
      HtjUtYFYhLBq71pAN3b7o3VoG9bGVuXU9gh1ryEkCgYBJMg1XEuHlA6LWulqJpRd
      IjkFUTxQOLqpbRX2eFexWqC7FzxUs+4+3yq25Vv+EN4Ho8K9k7Bk8E2oXsDw5Yeo
      XmVIsnyglcDBq5cLfXtv1+7QO93pZIBYlkXpH/XGmg8kVq95rKXWvX1w2efmqjtp
      yxlN2K2IldJ8QdqZxwnwzQKBgQDQl+gjE/BfQHs+rS2zZ2q4Lj+t22xx9q0xoz9A
      qqZxIHpC7r+4Oe7Pq09Qjk7fEcXTqUTdIsR8x/3GNHfv1tLwRpRfkRKg5Pz+nKO7
      xpq0Q3fw5P7i+m6/yCe6Rp2XrMxKZ6Ve8B9IfmZ2WvzHx6v3s8qwZfgoMCURfqHe
      2Oiw/wKBgQDIt/kKvW7WtFeXLNZ52UYz8eTkz4cPnpqg98o2zyqA4jM3dOXlcGpq
      Zc8hZ4lruXRo5gnKdfX+vBdIzjNfRAN1HxQlqaMRFtLzQb17AfXz8OTXm5zJXXVF
      kJjrX/48wGUcgB5hN8Gq++w4UVTE6VsnndID8S29r6Q9cZtRt2WfSg==
